# Generated by Django 3.2.2 on 2021-05-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='description',
            new_name='observation',
        ),
    ]
