# Generated by Django 3.2.2 on 2021-05-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_contato_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='city',
            new_name='name',
        ),
    ]
